security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        user_provider:
            id: App\BusinessService\UserProvider
    firewalls:
        login:
            pattern: ^/api/v1/login
            stateless: true
            json_login:
                check_path: /api/v1/login-check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api/v1
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/v1/login-check, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/users, roles: IS_AUTHENTICATED_FULLY, methods: [GET, PUT] }
        - { path: ^/api/v1/users, roles: PUBLIC_ACCESS, methods: POST }
        - { path: ^/api/v1, roles: IS_AUTHENTICATED_FULLY}

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
