version: '3.6'

services:
  gsws.back-web:
    container_name: gsws.back-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - '3000:80'
    volumes:
      - ./public:/appdata/www/public
    networks:
      - gsws-network
    depends_on:
      - gsws.back-be

  gsws.back-be:
    container_name: gsws.back-be
    build:
      context: ./docker/php
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    networks:
      - gsws-network
    depends_on:
      - gsws.database

  gsws.database:
    container_name: gsws.database
    build:
      context: ./docker/database
    ports:
      - '40000:3306'
    environment:
      MYSQL_DATABASE: gsws_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - gsws.database-data:/var/lib/mysql
    networks:
      - gsws-network

volumes:
  gsws.database-data:

networks:
  gsws-network:
    external: true
