# format: app.resource.method

# Login Resource
app.loginResource.login:
  path: /login
  controller: App\ApiController\LoginResource::login
  methods: [ GET ]

app.loginResource.createAccount:
  path: /create-account
  controller: App\ApiController\LoginResource::createAccount
  methods: [ POST ]

app.loginResource.changePassword:
  path: /change-password
  controller: App\ApiController\LoginResource::changePassword
  methods: [ GET ]