# format: app.controller.method

# Login Api Controller
app.loginApiController.login:
  path: /login
  controller: App\ApiController\LoginApiController::login
  methods: [ GET ]

app.loginApiController.createAccount:
  path: /create-account
  controller: App\ApiController\LoginApiController::createAccount
  methods: [ POST ]

app.loginApiController.changePassword:
  path: /change-password
  controller: App\ApiController\LoginApiController::changePassword
  methods: [ GET ]