app.users.login:
  path: /users
  controller: App\ApiController\LoginApiController::login
  methods: [ GET ]

app.users.login.check:
  path: /login-check

app.users.createAccount:
  path: /users
  controller: App\ApiController\LoginApiController::createAccount
  methods: [ POST ]
