app.loginApiController.login:
  path: /login
  controller: App\ApiController\LoginApiController::login
  methods: [ GET ]

app.loginApiController.createAccount:
  path: /create-account
  controller: App\ApiController\LoginApiController::createAccount
  methods: [ POST ]
