App\Dto\Input\UserLoginDto:
    properties:
        userName:
            - NotBlank: ~
            - Length:
                  min: 3
                  max: 255
                  minMessage: 'Your userName must be at least {{ limit }} characters long'
                  maxMessage: 'Your userName cannot be longer than {{ limit }} characters'
        password:
            - NotBlank: ~
            - Length:
                min: 6
                max: 255
                minMessage: 'Your Password must be at least {{ limit }} characters long'
                maxMessage: 'Your Password cannot be longer than {{ limit }} characters'

App\Dto\Input\UserInputDto:
    properties:
        userName:
            - NotBlank: ~
        password:
            - NotBlank: ~