App\Dto\Input\UserLoginDto:
    properties:
        userName:
            - NotBlank: ~
        password:
            - NotBlank: ~

App\Dto\Input\UserInputDto:
    properties:
        userName:
            - NotBlank: ~
        password:
            - NotBlank: ~
        roles:
            - NotBlank: ~