# format: app.controller.method

# Login Controller
app.loginController.login:
    path: /api/login/{userName}
    controller: App\Controller\Common\LoginController::login

app.loginController.createAccount:
    path: /api/create-account
    controller: App\Controller\Common\LoginController::createAccount
    methods: [ POST ]

app.loginController.changePassword:
    path: /api/change-password
    controller: App\Controller\Common\LoginController::changePassword
