# format: app.resource.method

# Login Resource
app.loginController.login:
    path: /api/login
    controller: App\ApiResource\LoginResource::login

app.loginController.createAccount:
    path: /api/create-account
    controller: App\Controller\Common\LoginController::createAccount
    methods: [ POST ]

app.loginController.changePassword:
    path: /api/change-password
    controller: App\Controller\Common\LoginController::changePassword
