# format: app.resource.method

# Login Resource
app.loginResource.login:
    path: /api/login
    controller: App\ApiResource\LoginResource::login
    methods: [ GET ]

app.loginResource.createAccount:
    path: /api/create-account
    controller: App\ApiResource\LoginResource::createAccount
    methods: [ POST ]

app.loginResource.changePassword:
    path: /api/change-password
    controller: App\ApiResource\LoginResource::changePassword
    methods: [ GET ]
