app_loginController-login:
    path: /api/login/{userName}
    controller: App\Controller\Common\LoginController::login

app_loginController-isLoggedOut:
    path: /api/isLoggedOut
    controller: App\Controller\Common\LoginController::isLoggedOut
