parameters:
    router.request_context.scheme: 'https'
    asset.request_context.secure: true

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Entity/'

    App\ApiController\:
        resource: '../src/ApiController'
        tags: ['controller.service_arguments']

    App\Exception\JsonTransformerExceptionListener:
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100}
