name: symfony

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install composer
      run: composer install
