name: symfony

on:
  push:
    branches:
      - "develop"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -uses: actions/checkout@v2
      -name: Install composer
      run: composer install
