name: SonarCloud Dev-Ops
on:
  push:
    branches: ['develop', 'release-*']
jobs:
  devops:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}
      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
          -Dsonar.projectKey=Kenny-Tinoco_GalyStudioWebSystem.Back
          -Dsonar.organization=jt-software
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}