name: SonarCloud Dev-Ops
on:
  push:
    branches: ['develop', 'release-*']
jobs:
  devops:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}
      - name: Run SonarCloud scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectKey=Kenny-Tinoco_GalyStudioWebSystem.Back
          -Dsonar.organization=jt-software
          -Dsonar.sources=src
          -Dsonar.language=php
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.exclusions=vendor/*
          -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}